version: "3"

services:
  textract:
    image: marcusvy/textract:1.5
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    container_name: textract
    working_dir: /data
    volumes: 
      - ./:/data
      